language: node_js
node_js:
- '0.10'
notifications:
  email: false
before_install: npm install -g grunt-cli
install: npm install
deploy:
  provider: heroku
  api_key: 1650e549-e7f4-4a0b-99fd-7b36d4231121
  app: week3
  on:
    repo: wanglina/week3
